tasks:
  - name: Setup PHP and MySQL
    init: |
      sudo apt update
      sudo apt install -y php php-mysql mariadb-server
      sudo service mysql start
      sudo mysql -e "CREATE DATABASE demo;"
      sudo mysql -e "CREATE USER 'gitpod'@'localhost' IDENTIFIED BY 'gitpod';"
      sudo mysql -e "GRANT ALL PRIVILEGES ON demo.* TO 'gitpod'@'localhost';"
      sudo mysql -e "FLUSH PRIVILEGES;"

ports:
  - port: 8000
    onOpen: open-preview
